my_array = [ 1, 2, 3, 4,]
my_nested_array = [ 5, 6, [ 1, 2, 3, 4,], 7,]
custom_array_test = [ 10, 20, 30,]
my_deep_nested_array = [ [ 1, 2, 3,], [ 4, 5, 6,], 99,]
my_sum = 30
my_sub = 35
my_mul = 30
my_pow = 8
my_mod = 1
expr_array = [ 1, 2, 10, 8,]
expr_nested_array = [ [ 1, 2, 3, 4,], 15, 17,]
my_complex_array = [ [ 1, 2, 3, 4,], "nested_array", 42, 30,]
my_reused_array = [ [ [ 1, 2, 3,], [ 4, 5, 6,], 99,], [ [ 1, 2, 3, 4,], "nested_array", 42, 30,], 75,]
my_string_array = [ "hello", "world", "parser", "test",]
my_mixed_array = [ 1, "text", 25, [ 1, 2, 3, 4,],]
my_combined_array = [ [ 10, 20,], 70, "deep_nested_array",]
