db_host = [ "'localhost'",]
db_port = [ 5432,]
db_user = [ "'admin'",]
db_password = [ "'secret'",]
db_name = [ "'myapp'",]
person_info = [ "'db_host'", "'db_port'", "'db_user'", "'db_password'", "'db_name'",]
server_name = [ "'myserver.com'",]
server_port = [ 80,]
document_root = [ "'/var/www/html'",]
index_file = [ "'index.html'",]
error_log = [ "'/var/log/nginx/error.log'",]
db_info = [ "'server_name'", "'server_port'", "'document_root'", "'index_file'", "'error_log'",]
