db_host = [ "'localhost'",]
db_port = [ "'5432'",]
db_user = [ "'admin'",]
db_password = [ "'secret'",]
db_name = [ "'myapp'",]
db_info = [ [ "'localhost'",], [ "'5432'",], [ "'admin'",], [ "'secret'",], [ "'myapp'",],]
server_name = [ "'myserver.com'",]
server_port = [ "'80'",]
document_root = [ "'/var/www/html'",]
index_file = [ "'index.html'",]
error_log = [ "'/var/log/nginx/error.log'",]
server_info = [ [ "'myserver.com'",], [ "'80'",], [ "'/var/www/html'",], [ "'index.html'",], [ "'/var/log/nginx/error.log'",],]
