db_host = [ "'localhost'",]
db_port = [ 5432,]
db_user = [ "'admin'",]
db_password = [ "'secret'",]
db_name = [ "'myapp'",]
server_name = [ "'myserver.com'",]
server_port = [ 80,]
document_root = [ "'/var/www/html'",]
index_file = [ "'index.html'",]
error_log = [ "'/var/log/nginx/error.log'",]
